# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js & Smart Contracts CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Truffle v5.5.12 Globally
      run: npm install truffle@5.5.12 -g
      
    - name: Install Dependencies from Main Lockfile
      run: npm ci
      
    - name: Install Dependencies from Frontend Lockfile
      run: npm ci
      working-directory: appfrontend
      
    - name: Compile Truffle Contracts
      run: truffle compile
      
    - name: Build Frontend
      run: CI=false npm run build --if-present #Override default behaviour as CI=true treats warnings as errors and fails build.
      working-directory: appfrontend
      
    - name: Test Frontend
      run: npm test
      working-directory: appfrontend
